### ISSUE TITLE
error in cast 

### ISSUE THREAD

**Issue by sattargharanjik** [shaon2016/Android-CleanArchitecture-MVVM-HILT#1]
hello
The problem I have
success.data cast to Data Model 

Error:  LinkedTreeMap Not Cast to Data Model

Please Help Me

how to Pars data to DataModel in handleSuccessfulResponse
success.data?

**Comment by shaon2016** [comment]
Plz follow the code. I have already added example in this project

**Comment by sattargharanjik** [comment]
There is no in the sample

MainActivity:

 if (success.type == User::class.java) {
            // TODO Do your work
        } else {
        }

How to get value  User data ?

**Comment by sattargharanjik** [comment]
This is my code:

```
 if (success.type == Verify::class.java) {
 val data = Gson().fromJson(success.data.toString(), Verify::class.java)
 Log.i("TAG", "AcsessToken: " + data.accessToken)
 }
 
```
 Error:
  com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 48 path $.message
  
  ---------------
Responses:

  Rsponse Json From Api :
  {"access_token":"212ds","success":"true","message":"ok verify"}
  
  Response in success.data :
  {access_token=212ds, success=true, message=ok verify}
  
  Error Not Pars 
  Error Not Cast to Verify Model

**Comment by sattargharanjik** [comment]
Please Help Me

**Comment by shaon2016** [comment]
Paste your verify model class here

**Comment by sattargharanjik** [comment]
is Model Class Gernerated by Kotlin data model generator plugin /  format: Gson

Verify Model Class: 

```
data class Verify(@SerializedName("access_token")
                 val accessToken: String = "",
                 @SerializedName("success")
                 val success: String = "",
                 @SerializedName("message")
                 val message: String = "")

```

Response Gson to LinkedTreeMap Format:
 {access_token=212ds, success=true, message=ok verify}

Now I get value in this case:
```
 if (success.type == Verify::class.java) {
            val lm  = success.data as LinkedTreeMap<*, *>
            Log.i("TAG", "AccessToken: " + lm.get("access_token"))
        }
```

But why can not Gson be output a model Class?

**Comment by sattargharanjik** [comment]
Please Help Me

**Comment by sattargharanjik** [comment]
Please Help Me

**Comment by shaon2016** [comment]
Is your log print
Success is boolean 
in your model class it is string
Why?

**Comment by sattargharanjik** [comment]
Was already in json and Model the Boolean 
After this problem changed to the string in json and model

**Comment by sattargharanjik** [comment]
Mr Shaon , this is my telegram id:
@setty69
or
Gmail:
sattar.ghranjik69@gmail.com

Please pm to connect remote (any desk) 
Please do this for servant

thank you very much

**Comment by sattargharanjik** [comment]
This code is not tested!!!
